/*
 *	Given two strings s and t which consist of only lowercase letters.
 *
 *	String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 *	Find the letter that was added in t.
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
    	int result = 0;
    	int cnt[256] = {0};
    	for(char c : s)	cnt[c]++;
    	for(char c : t) if(cnt[c]-- < ) return c;
    	return result;
    }
};
